name: "Build and deploy"

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Deploy
    runs-on: [self-hosted]

    steps:
      - name: Checkout and login
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          # tags: ${{ github.sha }}
          tags: latest
      
      - name: Set env
        run: echo "GH_REGISTRY_IMAGE=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io  # GitHub Container Registry
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # - uses: alex-ac/github-action-ssh-docker-compose@master
      #   name: Docker compose down
      #   with:
      #     ssh_host: ${{ secrets.SSH_SERVER }}
      #     ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ssh_user: ${{ secrets.SSH_USER }}
      #     docker_compose_prefix: 'gh_'
      #     docker_compose_down: 'true'

      # - uses: alex-ac/github-action-ssh-docker-compose@master
      #   name: Docker-Compose Remote Deployment
      #   with:
      #     ssh_host: ${{ secrets.SSH_SERVER }}
      #     ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ssh_user: ${{ secrets.SSH_USER }}
      #     docker_compose_prefix: 'gh_'