name: "Build and deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy (copy method)
    runs-on: [self-hosted]

    steps:
      - name: Checkout and login
        uses: actions/checkout@v3

      - name: Remove outdated file
        run: echo "${{ vars.WOKR_DIR }}"
