name: "Build and deploy"

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Deploy
    runs-on: [self-hosted]

    steps:
      - name: Checkout and login
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          # tags: ${{ github.sha }}
          tags: latest
      
      - name: Set env
        run: echo "GH_REGISTRY_IMAGE=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
      
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io  # GitHub Container Registry
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Remote auth Docker in GitHub Registry
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      
      - uses: matiasnu/github-action-ssh-docker-compose@v2.0.3
        name: Docker compose down
        with:
          ssh_host: ${{ secrets.SSH_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          docker_compose_prefix: 'gh_'
          docker_compose_down: 'true'
          docker_compose_filename: 'docker-compose.yml'

      - uses: matiasnu/github-action-ssh-docker-compose@v2.0.3
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: ${{ secrets.SSH_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          docker_compose_prefix: 'gh_'
          docker_compose_filename: 'docker-compose.yml'